name = "stargateedge"
type = "javascript" # or "webpack" if you are using webpack

account_id = "cd3e58766ea92897c4e633b4d7ee0380"
workers_dev = true
compatibility_date = "2025-04-09"

# Optional: You can specify the build command if needed
# [build]
# command = "npm run build"

# Optional: Environment-specific configurations
# [env.production]
# name = "stargateedge-production"
# route = "example.com/*"
# zone_id = "your-zone-id"
